clear all; close all; rehash;

FS = ThorlabsStage(...
	'stageId', get_com_port('FastStage'), ...
	'flagHome', 1);

SS = ThorlabsStage(...
	'stageId', get_com_port('SlowStage'), ...
	'flagHome', 1,...
    'mass',700);
